// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbvA-_w8TxkpVNEOhdjscxfEP2yv21fiE',
    appId: '1:350360634344:web:10390785b10a7fabd51a5d',
    messagingSenderId: '350360634344',
    projectId: 'labproject-af95f',
    authDomain: 'labproject-af95f.firebaseapp.com',
    databaseURL: 'https://labproject-af95f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'labproject-af95f.appspot.com',
    measurementId: 'G-Y93KYMLJDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBABDAzizsm_kEXDg6iCjoFVY6ZWHkEdDo',
    appId: '1:350360634344:android:df84654c9d0dab61d51a5d',
    messagingSenderId: '350360634344',
    projectId: 'labproject-af95f',
    databaseURL: 'https://labproject-af95f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'labproject-af95f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuakH8s7qWD9FNtnr6LdwheGUoivJi7wc',
    appId: '1:350360634344:ios:cc31abcd59c4a841d51a5d',
    messagingSenderId: '350360634344',
    projectId: 'labproject-af95f',
    databaseURL: 'https://labproject-af95f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'labproject-af95f.appspot.com',
    iosBundleId: 'com.example.labproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuakH8s7qWD9FNtnr6LdwheGUoivJi7wc',
    appId: '1:350360634344:ios:cc31abcd59c4a841d51a5d',
    messagingSenderId: '350360634344',
    projectId: 'labproject-af95f',
    databaseURL: 'https://labproject-af95f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'labproject-af95f.appspot.com',
    iosBundleId: 'com.example.labproject',
  );

}